export const FETCH_USERDATA_REQUEST = 'FETCH_USERDATA_REQUEST';
export const FETCH_USERDATA_SUCCESS = 'FETCH_USERDATA_SUCCESS';
export const FETCH_USERDATA_FAILED = 'FETCH_USERDATA_FAILED';

export const USERDATA_CHANGE_VIEW = 'USERDATA_CHANGE_VIEW';